---
- name: Run container
  hosts: application
  become: true
  roles:
    - role: containers/install
    - role: containers/login/filip
    - role: containers/run

  vars:
    container_name: web
    image_name: nginx #bara namnet
    tag: 1.29.4
    container_state: started
    container_ports:
      - "8080:80" # map host port 8080 to container 80
    container_env_vars:
    container_volumes:
    container_restart_policy: always
